rabble-app/supplement-club

- .github/pull_request_template.md
> feat: test pull request template

- src/components/dashboard/referral/ViewTrakingCard.tsx
- src/components/main/DesktopHeaderButtons.tsx
- src/components/main/products/PreOrderInfo.tsx
- src/components/main/products/ProductFaqs.tsx
- src/components/shared/ReferralCardsWithLink.tsx
> Make changes based on channel feedback

- src/app/(main)/products/[productID]/page.tsx
- src/app/dashboard/manage-plans/[subscriptionID]/top-up-checkout/page.tsx
- src/app/dashboard/view-past-orders/page.tsx
- src/components/dashboard/manage-plans/ManagePlanCard.tsx
- src/components/main/products/CapsuleBox.tsx
- src/components/main/products/CorporationCardInfo.tsx
- src/components/shared/ProductCard.tsx
- src/components/shared/SummaryProduct.tsx
- src/utils/helpers.ts
- src/utils/utils.ts
> Add minor changes

- src/components/shared/SummaryProduct.tsx
- Fix issues with payment page design
- Checked out issue with payment card addition
> fix: payment page

- src/app/(main)/products/[productID]/page.tsx
- src/components/main/products/CorporationCardInfo.tsx
- src/components/main/products/ImageBox.tsx
- src/components/main/products/TeamPrice.tsx
- src/components/shared/ProductCard.tsx
- src/components/shared/SummaryProduct.tsx
- src/components/ui/carousel.tsx
Fronted Fixes
- Implement sticky nav for "Start my supplement button"
- Resolve supplement product name that is joined together
- Resolve icon image alt that was showing path instead of category name
- Take away slider button when there is no other image to view
> chore:frontend designs

- src/components/main/ProductInfo.tsx
> Make changes on product info on home page based on figma

- src/app/(main)/page.tsx
> Changed text

- src/components/main/Header.tsx
> Make changes on text + stick to the top on scrolling

- src/components/ui/breadcrumb.tsx
> Make changes on font for breadcrumb

- src/components/shared/PaymentList.tsx
> Add hyperlink to the payment page

- src/components/shared/ProductCard.tsx
- src/utils/utils.ts
> Make changes on related with price, RRP, Discount, Members

- src/app/(main)/page.tsx
> Words descriptions should both be stacked

- src/app/(main)/labs/page.tsx
- src/app/(main)/page.tsx
- src/app/(main)/products/page.tsx
- src/components/main/products/ExpansionSelector.tsx
Mark selected categories/goals on products page.
When navigate category from home page, it redirects to products page. So here, were added category selected based on chosen one.
> Include selected category/goal on product page

- package.json
- src/app/(main)/page.tsx
- src/app/(main)/products/[productID]/checkout/page.tsx
- src/app/(main)/products/[productID]/page.tsx
- src/app/dashboard/layout.tsx
- src/app/dashboard/manage-plans/[subscriptionID]/page.tsx
- src/app/dashboard/manage-plans/page.tsx
- src/app/layout.tsx
- src/components/dashboard/subscription-managment/SubscriptionPlan.tsx
- src/components/main/DesktopHeaderButtons.tsx
- src/components/main/Header.tsx
- src/components/main/products/CapsuleBox.tsx
- src/components/main/products/CorporationCardInfo.tsx
- src/components/main/products/TeamPrice.tsx
- src/components/main/products/[productID]/checkout/AlignmentDialog.tsx
- src/components/main/products/[productID]/checkout/DeliveryAddress.tsx
- src/components/shared/OrderSummaryCard.tsx
- src/components/shared/SummaryProduct.tsx
- src/utils/models/api/IUserPlanResponse.ts
- src/utils/models/api/response/IUserPlanResponse.ts
> feat: sc updates

- src/components/dashboard/UpcomingDeliverySlider.tsx
> chore: update to upcoming delivery

- src/components/main/products/[productID]/checkout/AlignmentDialog.tsx
> chore: update

- src/components/main/products/[productID]/checkout/AlignmentDialog.tsx
> chore: button design margin

- src/app/(main)/page.tsx
- src/app/(main)/products/[productID]/page.tsx
- src/components/main/products/CapsuleBox.tsx
- src/components/main/products/MemberCard.tsx
- src/components/main/products/TeamPrice.tsx
- src/components/main/products/[productID]/checkout/AlignmentDialog.tsx
- src/components/shared/OrderSummaryCard2.tsx
- src/components/shared/ProductCard.tsx
- src/components/shared/SummaryProduct.tsx
- src/hooks/useProduct.ts
- src/services/productService.ts
- src/services/usersService.ts
- src/utils/mapping.ts
- src/utils/models/IProductCardModel.ts
- src/utils/models/ISummaryProductModel.ts
- src/utils/models/api/response/IProductResponse.ts
- src/utils/utils.ts
> chore: updates

- src/app/(main)/labs/page.tsx
- src/app/(main)/page.tsx
> fix: deployment

- src/components/shared/ProductCard.tsx
- src/components/shared/SummaryProduct.tsx
- src/utils/utils.ts
> chore: fixes for 11th August

- src/app/(main)/products/[productID]/checkout/page.tsx
- src/app/dashboard/manage-plans/[subscriptionID]/opt-back-in/page.tsx
- src/components/dashboard/manage-plans/ManagePlanCard.tsx
- src/components/dashboard/referral/ReferalLinkCard.tsx
- src/components/dashboard/subscription-managment/OptBackInDialog.tsx
- src/components/main/Header.tsx
- src/components/main/products/CapsuleBox.tsx
- src/components/main/products/[productID]/checkout/AlignmentDialog.tsx
- src/components/main/products/[productID]/checkout/ConfirmJoining.tsx
- src/components/shared/AlignmentDialogueEditableBox.tsx
- src/components/shared/ReferralCardsWithLink.tsx
- src/components/shared/SummaryProduct.tsx
- src/components/shared/SummaryProduct2.tsx
- src/hooks/useFirst30Days.ts
- src/hooks/useProduct.ts
- src/services/productService.ts
- src/utils/helpers.ts
- src/utils/mapping.ts
- src/utils/models/IOrderPackageModel.ts
- src/utils/models/ISingleProductModel.ts
- src/utils/models/api/IProductModel.ts
- src/utils/models/api/response/IUserResponse.ts
> chore: stock level
